#!/usr/bin/bash

echo "==================== post-merge hook ===================="

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_env(){
	echo "$change_files" | grep --quiet $1 && eval "$2" && echo "Updated conda environment."
}

check_env env.yaml "conda env update --file env.yaml"
