# PATHS
data_folder: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/MutSeqGenerator/tumors"
output: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/data/TCGA_haplotype_association/TCGA"
wt_transcripts: "/shares/CIBIO-Storage/BCG/scratch/fgastaldello/resources/protein_coding_transcripts"
pathway_alteration_table: "/shares/CIBIO-Storage/BCG/scratch1/Resources/TCGA/dataTabs/somaticAlterations/10oncogenicPathways/1-s2.0-S0092867418303593-mmc4.xlsx"
tumor_subtypes_list: "/shares/CIBIO-Storage/BCG/scratch1/Resources/TCGA/dataTabs/Cancer_subtypes_list.tsv"
clinical_data: "/shares/CIBIO-Storage/BCG/scratch1/Resources/TCGA/data/combined_study_clinical_data.tsv"
PCs: "/shares/CIBIO-Storage/BCG/scratch1/Resources/TCGA/PCs/TCGA_Affy_all.eigenvec"
plink2: "/shares/CIBIO-Storage/BCGLAB/Tools/plink2.0/plink2a4.6"

# WILDCARDS
cancer_types: ["DLBC","ACC","BLCA","BRCA","CESC","CHOL","COAD","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LGG","LIHC","LUAD","LUSC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THCA","THYM","UCEC","UCS"]
# "UVM","DLBC","ACC","BLCA","BRCA","CESC","CHOL","COAD","ESCA","GBM","HNSC","KICH","KIRC","KIRP","LAML","LGG","LIHC","LUAD","LUSC","MESO","OV","PAAD","PCPG","PRAD","READ","SARC","SKCM","STAD","TGCT","THCA","THYM","UCEC","UCS"

# ANALYSIS TYPE
tumor_subtypes:     FALSE
tumor_vs_tumor:     TRUE
pathway_alteration: FALSE

# PLINK2 MODELS

# Plink includes the model used in the output filename. Since the additive model is used
# by default, the name would have a blank spot creating problems to snakemake.
# so hide-cover is used as placeholder for the additive output filename
model: ["hide-covar", "dominant", "recessive" ]


# CORES
haplotype_ID_cores: 50
make_vcf_tt_cores: 3
plink_glm_cores: 1
check_pval_cores: 30
log_reg_cores: 30